README.md, src/command.coffee, test/index.coffee
=> command: use safe exit code in case of test failures

package.json, src/doctest.coffee
=> ramda@0.10.x

.travis.yml, Makefile, README.md, bin/doctest, bower.json, package.json, src/command.coffee, src/doctest.coffee, test/harmony/index.js, test/harmony/results.js, test/index.coffee
=> switch to esprima-fb for Harmony support

bower.json, package.json, src/doctest.coffee
=> ramda@0.11.x

LICENSE, package.json
<https://docs.npmjs.com/files/package.json#license>
=> update licence metadata

README.md
Supersedes #26
Does this look good to you, @mkllnk?
=> readme: expand introductory paragraph

lib/command.js, lib/doctest.js, test/index.js, test/transcribe/index.coffee, test/transcribe/index.js, test/transcribe/results.js
Closes #63
How does this look to you, @danse?
=> add "prefix" option for Transcribe compatibility

bower.json, package.json
=> ramda@0.19.x

Makefile, README.md, package.json
https://github.com/jquery/esprima/compare/2.6.0...3.1.3
=> esprima@3.1.x

lib/doctest.js, test/index.js, test/statements/index.js, test/statements/results.js
=> support input statements in JavaScript files

.travis.yml, Makefile, lib/doctest.js, package.json, test/index.js
https://github.com/sanctuary-js/sanctuary-style/compare/v0.4.0...v0.5.0
=> sanctuary-style@0.5.x

package.json
<https://github.com/sanctuary-js/sanctuary-style/releases/tag/v1.0.0>
=> sanctuary-style@1.0.x

Makefile, package.json
<https://github.com/sanctuary-js/sanctuary-style/releases/tag/v1.1.0>
=> sanctuary-style@1.1.x

README.md
This adds a little colour to the readme. :art:
=> readme: enable highlighting of code blocks

README.md
=> readme: document input/output wrapping

package.json
<https://github.com/jquery/esprima/blob/4.0.0/ChangeLog>
=> esprima@4.0.x

lib/doctest.js, test/index.js
Module tests have been disabled since I mistakenly removed `testModule` in #86. :scream:
=> test: reinstate testModule

package.json
- <https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v8.2.0>
- <https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v8.2.1>
=> sanctuary-type-classes@8.2.x

package.json
<https://github.com/sanctuary-js/sanctuary-type-classes/releases/tag/v9.0.0>
=> sanctuary-type-classes@9.0.x

package.json
<https://coffeescript.org/v1/#changelog>
Upgrading to CoffeeScript 2 is not a trivial task as it would require the use of a transpiler in older environments. I'll only undertake this work if someone requests it. :)
=> coffeescript@1.12.x

package.json, scripts/lint-readme
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v1.5.0>
=> sanctuary-scripts@1.5.x

.eslint.js, .eslintignore, .travis.yml, package.json
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v3.0.0>
This pull request includes a workaround for eslint/eslint#10587.
=> sanctuary-scripts@3.0.x

bin/doctest, scripts/lint
This pull request should be merged before #113 is merged.
=> lint: reformat bin/doctest to appease ESLint

package.json
<https://github.com/tj/commander.js/releases/tag/v2.20.0>
=> commander@2.20.x

.travis.yml, bin/doctest, lib/command.mjs, lib/doctest.mjs
Related to https://github.com/sanctuary-js/sanctuary/pull/640
=> Support Node 12

.travis.yml
https://nodejs.org/en/about/releases/
=> Travis CI: Drop EOL versions of Node.js

.eslint.js, .eslintignore, package.json
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v4.0.0>
=> sanctuary-scripts@4.0.x

.config, .eslintrc.json, README.md, package.json, scripts/lint, scripts/lint-readme
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v5.0.0>
=> sanctuary-scripts@5.0.x

README.md
The JavaScript interface was changed in #125.
=> readme: fix examples of JavaScript interface

README.md
=> readme: update protocols

lib/doctest.js, test/es2020/index.js, test/es2020/results.json, test/index.js
Supersedes #130
/cc @EricLanduyt
=> support ECMAScript 2020

package.json
<https://github.com/acornjs/acorn/blob/8.5.0/acorn/CHANGELOG.md>
=> acorn@8.5.x

package.json
<https://github.com/babel/babel-eslint/releases/tag/v10.1.0>
=> babel-eslint@10.1.x

lib/doctest.js
I would rather accept some duplication than a complicated procedure that mutates one of its inputs.
=> remove ‘processLine’

package.json
<https://coffeescript.org/#changelog>
=> coffeescript@2.6.x

lib/Comparison.js, lib/Effect.js, lib/Line.js, lib/command.js, lib/doctest.js, test/bin/results.js, test/commonjs/__dirname/results.js, test/commonjs/__doctest.require/results.js, test/commonjs/__filename/results.js, test/commonjs/exports/results.js, test/commonjs/module.exports/results.js, test/commonjs/require/results.js, test/commonjs/strict/results.js, test/es2015/results.js, test/es2018/results.js, test/es2020/results.js, test/exceptions/index.js, test/exceptions/results.js, test/fantasy-land/index.js, test/fantasy-land/results.js, test/index.js, test/line-endings/results.js, test/shared/results.coffee.js, test/shared/results.js, test/statements/results.js, test/transcribe/results.js
These (breaking) changes to the return type have already been reviewed in #155; I decided to move them to a dedicated pull request to make that pull request clearer.
=> update return type

package.json
<https://github.com/acornjs/acorn/blob/8.11.2/acorn/CHANGELOG.md>
=> acorn@8.11.x

package.json
<https://coffeescript.org/#changelog>
=> coffeescript@2.7.x

package.json
<https://github.com/bearror/oletus/compare/v3.2.0...285b30b9bc412d23c19ff9121201956b416e5fbc>
=> oletus@4.0.x

.config, .eslintrc.json, package.json, scripts/test
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v6.0.0>
=> sanctuary-scripts@6.0.x

.github/workflows/test.yml, lib/doctest.js, lib/require.js, package.json, test/esm/dependencies.js, test/index.js
[New in Node.js: `node:` protocol imports][1]
[1]: https://2ality.com/2021/12/node-protocol-imports.html
=> use `node:` imports
