Makefile, README.md, bower.json, package.json, src/command.coffee, src/doctest.coffee, test/index.coffee, test/index.html
Ramda's `eqDeep` is not identical to Underscore's `isEqual`, but should be equivalent for common comparisons.
=> remove Underscore dependency

.travis.yml, test/index.coffee
Switching to [`child_process.execSync`][1] (from [`child_process.exec`][2]) is not strictly necessary but it greatly simplifies matters. Since the function was added in [Node v0.12.0][3], the test suite can no longer be run on older versions.
[1]: https://nodejs.org/api/child_process.html#child_process_child_process_execsync_command_options
[2]: https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback
[3]: https://nodejs.org/en/blog/release/v0.12.0/
=> specify appropriate exit code in test/index.coffee

src/doctest.coffee, test/shared/results.js
It's intuitive for the actual value to precede the expected value since the input precedes the expected output in the doctest itself.
=> switch actual and expected values in quadruples

README.md, bower.json, package.json, src/doctest.coffee, test/amd/results.js, test/bin/results.js, test/commonjs/exports/results.js, test/commonjs/module.exports/results.js, test/commonjs/strict/results.js, test/exceptions/index.js, test/exceptions/results.js, test/harmony/results.js, test/index.coffee, test/index.html, test/line-endings/results.js, test/shared/index.coffee, test/shared/index.js, test/shared/results.js
This pull request allows doctests to leverage the full power of [`R.equals`][1]. For example:
```javascript
// > R.map(R.inc, S.Just(42))
// S.Just(43)
```
Previously one might have written:
```javascript
// > R.toString(R.map(R.inc, S.Just(42)))
// 'Just(43)'
```
This pull request also clarifies and enhances the testing of expected exceptions:
> __Exceptions__
>
> An output line beginning with EXCLAMATION MARK (`!`) indicates that the preceding expression is expected to throw. The exclamation mark *must* be followed by SPACE (<code> </code>) and the name of an Error constructor. For example:
>
> ```javascript
> // > null.length
> // ! TypeError
> ```
>
> The constructor name *may* be followed by COLON (`:`), SPACE (<code> </code>), and the expected error message. For example:
>
> …
=> ramda@0.17.x

scripts/prepublish, src/command.coffee, src/doctest.coffee
Including the `version` property adds complexity to the release process without much compensating benefit. One can still access the value in Node via `require('doctest/package.json').version`, and on the command-line via `doctest --version`.
=> remove "version" property from module

package.json
It's nice to exclude the tests and other unnecessary files from the distribution.
=> package.json: specify files to be included in tarball

bower.json, lib/doctest.js, package.json
ramda/ramda#1436
In v0.18.0, `R.converge` became a binary function (rather than a variadic function).
The following are equivalent:
```javascript
//  v0.17.x
R.converge(Math.pow, R.dec, R.inc)(3)
//  v0.18.x
R.converge(Math.pow, [R.dec, R.inc])(3)
//  v0.18.x
R.lift(Math.pow)(R.dec, R.inc)(3)
```
I decided to replace all occurrences of `R.converge(f)`. Some I replaced with `R.lift(f)`; others I replaced with lambdas.
Mind taking a look at this, @danse?
=> ramda@0.18.x

Makefile, bower.json, lib/doctest.js, package.json, test/fantasy-land/index.js, test/fantasy-land/results.js, test/index.js
Ramda currently supports an old version of the [Fantasy Land][1] specification (ramda/ramda#1900). In order to use doctest with types which target more recent versions of the specification we must use [`Z.equals`][2] in place of [`R.equals`][3].
[1]: https://github.com/fantasyland/fantasy-land
[2]: https://github.com/sanctuary-js/sanctuary-type-classes/tree/v4.0.0#equals
[3]: http://ramdajs.com/0.19.1/docs/#equals
=> use Z.equals for equality checks

lib/doctest.js, test/index.js
See sanctuary-js/sanctuary#470 for the motivation behind this addition.
=> expose ‘require’ as ‘__doctest.require’

Makefile, lib/command.js, lib/doctest.js, package.json, test/index.js
This pull request excites me for several reasons:
- it removes a dependency;
- it removes more code than it adds; and
- it dramatically improves performance.
Initially this project depended on [`_.isEqual`][1]. Back in #49 we switched to the Ramda equivalent, then known as [`R.eqDeep`][2], now known as [`R.equals`][3]. We currently depend on sanctuary-type-classes so we can use [`Z.equals`][4] instead.
I replaced uses of Ramda functions with uses of built-in methods where applicable (`Array#reduce` in place of `R.reduce`, for example). In the process, I also significantly simplified several algorithms (the `substring` function provides a striking example). The results are impressive: on my computer, running `node_modules/.bin/doctest --module commonjs --prefix . -- index.js` for …
=> remove Ramda dependency

lib/command.js, test/index.js
Years ago I chose to use `String#toLowerCase` to match the format of [Commander.js][1] error messages. This was unwise, as I recently discovered when doctest misreported an error as `sum is not defined` rather than `Sum is not defined`, while testing a module containing both `sum` and `Sum`. Confusing!
[1]: https://github.com/tj/commander.js
=> simplify formatting of error messages

lib/doctest.js, package.json
<https://www.npmjs.com/package/coffee-script>:
> # This package has been deprecated
>
> Author message:
>
> `CoffeeScript on NPM has moved to "coffeescript" (no hyphen)`
=> coffeescript@1.10.x

lib/doctest.js, package.json, test/fantasy-land/index.js, test/fantasy-land/results.json
[`show`][1] replaces [`Z.toString`][2]. Switching will make doctest compatible with Sanctuary's various algebraic data types, which will soon define `@@show` but not `toString`.
[1]: https://github.com/sanctuary-js/sanctuary-show#show
[2]: https://github.com/sanctuary-js/sanctuary-type-classes/tree/v8.1.1#toString
=> use sanctuary-show for string representations

lib/command.js, package.json, test/index.js
<https://github.com/tj/commander.js/releases>
The formatting of [Commander.js][1] error messages has changed; I updated `formatErrors` to match.
[1]: https://github.com/tj/commander.js
=> commander@2.19.x

lib/command.js, lib/doctest.js, package.json, test/index.js
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v2.0.0>
@danse, read sanctuary-js/sanctuary#438 if you're interested in the reasons for writing `f (x)` rather than `f(x)`.
=> sanctuary-scripts@2.0.x

lib/doctest.js
We should use these identifiers consistently rather than hard-code their values in some places.
=> use ‘INPUT’ and ‘OUTPUT’ constants

.eslintrc.json, .travis.yml, README.md, bin/doctest, lib/command.js, lib/command.mjs, lib/common.js, lib/doctest.js, lib/doctest.mjs, lib/program.js, package.json, test/esm/dependencies.mjs, test/esm/incorrect.mjs, test/esm/index.mjs, test/index.js
I started this a long time ago, but never finished it. Today I spent a few minutes adding the finishing touches, although completely untested and written by hand.
Edit: closes #99
=> ESM support

lib/doctest.js, lib/doctest.mjs
The new order of __doctest.js__ is much more sensible:
```
inferType
indentN
quote
wrap$js
wrap$coffee
-> indentN
processLine
normalizeTest
-> quote
transformComments
-> processLine
-> normalizeTest
substring
rewrite$js
-> wrap$js
-> transformComments
-> substring
rewrite$coffee
-> indentN
-> wrap$coffee
-> processLine
-> normalizeTest
arrowWrap
-> indentN
toModule
-> arrowWrap
show
run
-> show
commonjsEval
-> run
functionEval
-> run
evaluate
-> commonjsEval
-> functionEval
log
module.exports
-> inferType
-> rewrite$js
-> rewrite$coffee
-> toModule
-> evaluate
-> log
```
=> rearrange functions in dependency order

.travis.yml, package.json
[2018-05-23, Version 10.2.0 (Current), @MylesBorins][1]:
>   - __esm__:
>       - Builtin modules (e.g. `fs`) now provide named exports in ES6 modules. (Gus Caplan) [#20403][2]
[1]: https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.2.0
[2]: https://github.com/nodejs/node/pull/20403
=> update Node.js version range

.config, .gitignore, lib/doctest.js, package.json, scripts/test, test/index.js
Thanks to #146 we can now use [oletus][1] and [c8][2] for testing and coverage. Until these are included in [sanctuary-scripts][3] we will depend on them directly.
The source code is unchanged but for the addition of three `/* c8 ignore next */` directives. These are workarounds for bugs in V8's coverage reporting. These bugs have already been fixed; the directives are unnecessary when using v16.0.0.
[1]: https://www.npmjs.com/package/oletus
[2]: https://www.npmjs.com/package/c8
[3]: https://www.npmjs.com/package/sanctuary-scripts
=> test: integrate oletus and c8

lib/doctest.js, test/index.js
Currently we require `--type js` or `--type coffee` for files without extensions. It seems reasonable to assume that any file without the __.coffee__ extension is a JavaScript file (one can still specify `--type coffee` if necessary).
=> assume JavaScript

lib/command.js, lib/doctest.js, test/index.js
`doctest -- *.js` should succeed if no file path matches the glob.
=> command: use exit code 0 if no files are specified

lib/doctest.js, lib/program.js, test/index.js
Eventually I would like CoffeeScript support to be an optional extra.
=> remove file type inference in favour of ‘coffee’ flag

.github/workflows/test.yml, lib/doctest.js, package.json, test/index.js
Node.js 12 is no longer maintained ([release schedule][1]).
[1]: https://github.com/nodejs/release#release-schedule
=> require Node.js 14 or higher

test/index.js
This formatting change improves readability and will reduce diff noise in the future. :)
=> test: reformat ‘testModule’ applications

test/index.js, test/shared/results.js
Improvements:
- `doctest` is now run once per module rather than once per test case;
- the actual number of test cases must now match the expectation; and
- descriptions printed by the test runner are now more informative.
=> test: improve ‘testModule’

test/exceptions/index.js, test/exceptions/results.js, test/shared/index.coffee, test/shared/index.js, test/shared/results.coffee.js, test/shared/results.js
`null.length` is problematic because it behaves differently on different (supported) versions of Node.js:
```console
$ ASDF_NODEJS_VERSION=16.8.0 node --eval 'try { null.length } catch (err) { console.log (err.message) }'
Cannot read property 'length' of null
$ ASDF_NODEJS_VERSION=16.9.0 node --eval 'try { null.length } catch (err) { console.log (err.message) }'
Cannot read properties of null (reading 'length')
```
Currently doctest provides string representations of actual and expected values:
```javascript
'! Error: Invalid value'
```
String representations are to be replaced with rich values in #155:
```javascript
Failure (new Error ('Invalid value'))
```
I want to avoid conditional logic in the test suite:
```javascript
Failure (new TypeError (
nodeVersion.major < 16 || …
```
=> test: replace ‘null.length’ with ‘0..toString(1)’

lib/doctest.js, test/contiguity/index.coffee, test/contiguity/index.js, test/contiguity/results.js, test/index.js
Closes #120
The result format now provides a line number for each input line and each output line, facilitating contiguity checks.
I took this opportunity to make other changes to the result format. :)
/cc @kocielnik
=> require output lines to be contiguous with input lines

bin/doctest, lib/doctest.js, scripts/test, test/commonjs/__dirname/index.coffee, test/commonjs/__dirname/index.js, test/commonjs/__dirname/results.coffee.js, test/commonjs/__filename/index.coffee, test/commonjs/__filename/index.js, test/commonjs/__filename/results.coffee.js, test/esm/globals/index.js, test/esm/globals/results.js, test/index.js
This pull request changes the ways in which rewritten source text is evaluated, as described in the sections below.
---
__ES modules__ (`--module esm`)
Previously, in `evaluateModule`, the modified source was written to a temporary file which was then imported via `import()`.
Now, in `evaluateModule`, the modified source is evaluated using [`vm.SourceTextModule`][1] with `{...global}` as the context.
- ✔︎ Nothing is now written to the file system.
---
__CommonJS modules__ (`--module commonjs`)
Previously, in `commonjsEval`, the modified source was written to a temporary file which was then imported via `require()`.
Now, in `evaluateScript`, the modified source is evaluated using [`vm.runInNewContext`][2] with `{...global, process, exports, module, require, __dirname, __filename}` as the …
=> use vm module for evaluation

package.json
This dependency was added in #113, and was necessary at that time.
=> remove unused babel-eslint dependency

lib/doctest.js
This permits doctests in modules that use 2021/2022/2023 language features.
=> change `ecmaVersion` from `2020` to `2023`

.github/workflows/test.yml, bin/doctest, lib/doctest.js, package.json
This pull request fixes our handling of import declarations.
Currently only absolute specifiers such as `import util from 'node:util'` are interpreted correctly:
- `import foo from './foo.js'` attempts to import `[[doctest]]/lib/foo.js`; and
- `import bar from 'bar'` attempts to load the main entry point of `[[doctest]]/node_modules/bar`.
This bug does not just affect import declarations *within* doctests: top-level import declarations are also affected.
The fix involves using [`import.meta.resolve`][1] to resolve the module specifier. We provide an argument for the non-standard [`parent`][2] parameter Node.js supports when the `--experimental-import-meta-resolve` flag is specified. This makes module resolution relative to the module in which the import declaration appears, as expected. …
=> use `import.meta.resolve` to support relative and bare specifiers

lib/doctest.js
This pull request changes `wrapCoffee` to indent the generated code appropriately, obviating the need for `indentN`.
=> remove `indentN`

.config, .eslintrc.json, package.json, scripts/test
<https://github.com/sanctuary-js/sanctuary-scripts/releases/tag/v7.0.0>
Unfortunately we're not (yet) able to remove our custom `test` script as we need to specify `--experimental-vm-modules`.
The updated `test` script is a slightly modified version of the canonical one:
```
$ diff <(curl -Ls https://github.com/sanctuary-js/sanctuary-scripts/raw/v7.0.0/bin/test) scripts/test
4,6c4
< source "$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")/functions"
< 
< run_custom_script test "$@"
---
> source "$(dirname "$(dirname "$(realpath "${BASH_SOURCE[0]}")")")/node_modules/sanctuary-scripts/functions"
27c25
< node_modules/.bin/c8 "${args[@]}" -- node_modules/.bin/oletus -- "${test_files[@]}"
---
> node_modules/.bin/c8 "${args[@]}" -- node --experimental-vm-modules -- …
```
=> sanctuary-scripts@7.0.x

lib/doctest.js, test/index.js
I made some of these internal changes a few *years* ago. :see_no_evil:
Here is the new algorithm (with slight variations due to differences in the way comments are located):
```console
$ awk '$2 ~ /rewrite(Js|Coffee)/ { print $2; look = 1 } $0 == "};" { look = 0 } look && $1 == "//" && $2 ~ /:$/ { print }' lib/doctest.js
rewriteJs
// 1: Parse source text to extract comments
// 2: Preserve source text between comments
// 3: Extract prefixed comment lines
// 4: Coalesce related input and output lines
// 5: Convert doctests to source text
// 6: Sort verbatim and generated source text by original offsets
// 7: Concatenate source text
rewriteCoffee
// 1a: Extract prefixed comment lines
// 1b: Preserve other lines
// 2: Coalesce related input and output lines
// 3: Convert doctests to source …
```
=> refactor `rewriteJs` and `rewriteCoffee`
